# Generated by Django 3.0.5 on 2020-05-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'artículo'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'restaurante'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug_name',
            field=models.SlugField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
