# Generated by Django 3.0.5 on 2020-05-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200503_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug_name',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
