# Generated by Django 3.0.5 on 2020-05-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200503_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
