# Generated by Django 3.0.6 on 2020-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('alias', models.CharField(max_length=50, verbose_name='alias')),
                ('indoor_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='número interior')),
                ('latitude', models.FloatField(verbose_name='latitud')),
                ('longitude', models.FloatField(verbose_name='longitud')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
            },
        ),
    ]
