# Generated by Django 3.0.5 on 2020-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='formatted_address',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
