# Generated by Django 3.0.5 on 2020-05-04 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20200430_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('indoor_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='número interior')),
                ('latitude', models.FloatField(verbose_name='latitud')),
                ('longitude', models.FloatField(verbose_name='longitud')),
            ],
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='id',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='indoor_number',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='name',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='addresses.Address'),
            preserve_default=False,
        ),
    ]
