# Generated by Django 3.0.5 on 2020-05-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20200503_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'dirección', 'verbose_name_plural': 'direcciones'},
        ),
    ]
