# Generated by Django 3.0.6 on 2020-05-06 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0005_auto_20200503_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alias',
            field=models.CharField(default='', max_length=50, verbose_name='alias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
