# Generated by Django 3.0.6 on 2020-05-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200506_0437'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='current_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order', verbose_name='orden'),
        ),
    ]
