# Generated by Django 3.0.6 on 2020-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='es staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='es superusuario')),
                ('is_delivery_man', models.BooleanField(default=False, verbose_name='es repartidor')),
                ('is_admin', models.BooleanField(default=False, verbose_name='es administrador')),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='id de cliente de stripe')),
                ('status', models.PositiveSmallIntegerField(choices=[('Comensal', 1), ('Repartidor', 2), ('Administrador', 3)], default=1)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
            },
        ),
    ]
