# Generated by Django 3.0.6 on 2020-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('image', models.ImageField(upload_to='items', verbose_name='imagen')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('price', models.FloatField(verbose_name='precio')),
            ],
            options={
                'verbose_name': 'artículo',
            },
        ),
    ]
