# Generated by Django 3.0.6 on 2020-05-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('image', models.ImageField(upload_to='items', verbose_name='imagen')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('price', models.FloatField(verbose_name='precio')),
            ],
            options={
                'verbose_name': 'artículo',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0, verbose_name='total')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'carrito de compras',
                'verbose_name_plural': 'carritos de compras',
            },
        ),
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='cantidad')),
                ('subtotal', models.FloatField(verbose_name='subtotal')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Item', verbose_name='artículo')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ShoppingCart', verbose_name='carrito de compras')),
            ],
            options={
                'verbose_name': 'conjunto de artículos',
                'verbose_name_plural': 'conjuntos de artículos',
            },
        ),
    ]
