# Generated by Django 3.0.7 on 2020-06-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Sopa', 1), ('Platillo Fuerte', 2), ('Postre', 3), ('Bebida', 4), ('Otros', 0)], default=0, verbose_name='categoría'),
        ),
    ]
