# Generated by Django 3.0.7 on 2020-06-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sopa'), (2, 'Platillo Fuerte'), (3, 'Antojitos'), (4, 'Postre'), (5, 'Bebida'), (0, 'Otros')], default=0, verbose_name='categoría'),
        ),
    ]
