# Generated by Django 3.0.6 on 2020-05-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_itemset_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemset',
            options={'verbose_name': 'conjunto de artículos', 'verbose_name_plural': 'conjuntos de artículos'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'carrito de compras', 'verbose_name_plural': 'carritos de compras'},
        ),
    ]
